service: dogue-bi

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  environment: ${file(./env.yml)}
  stage: prod

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true # enable auto including modules
  serverless-offline:
    babelOptions:
      presets: ["node6", "stage-2"]

functions:
  calcReport:
    timeout: 300
    description: Calc report
    memorySize: 256
    handler: handler.calcReport

